# Generated by Django 5.2.17 on 2026-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0002_auto_20240216_1307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="contenido",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
