# Generated by Django 5.2.17 on 2026-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TiendaApp", "0003_auto_20240216_1307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaprod",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
