# Generated by Django 5.2.17 on 2026-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ServiciosApp", "0003_auto_20240216_1307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="contenido",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
